// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRhL1YbFWCR_yKpEy0CvYLfXdXB-jk_8',
    appId: '1:1021687426604:android:af81d5b451415e115b2b89',
    messagingSenderId: '1021687426604',
    projectId: 'manunited-trivia',
    storageBucket: 'manunited-trivia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-abicBic7kYiRuSg2Xn8TZqGwqXEtmos',
    appId: '1:1021687426604:ios:75e9766a64bd7ab25b2b89',
    messagingSenderId: '1021687426604',
    projectId: 'manunited-trivia',
    storageBucket: 'manunited-trivia.appspot.com',
    iosBundleId: 'com.example.manunitedTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-abicBic7kYiRuSg2Xn8TZqGwqXEtmos',
    appId: '1:1021687426604:ios:75e9766a64bd7ab25b2b89',
    messagingSenderId: '1021687426604',
    projectId: 'manunited-trivia',
    storageBucket: 'manunited-trivia.appspot.com',
    iosBundleId: 'com.example.manunitedTrivia',
  );
}
